services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile.laravel
    develop:
      watch:
        - path: ./
          target: /var/www/html
          action: sync          
    depends_on:
      - mysql
    ports:
      - 80:80
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    ports:
      - 8080:8080
    depends_on:
      - laravel
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
  phpmyadmin:
    image: phpmyadmin:5.1
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_PORT: ${DB_PORT}
    ports:
      - 8888:80
    depends_on:
      - mysql
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
