services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile.laravel
    develop:
      watch:
        - action: sync
          path: ./
          target: /var/www/html
        - action: rebuild
          path: composer.json
    depends_on:
      - mysql
    ports:
      - 80:80
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    develop:
      watch:
        - action: rebuild
          path: package.json
    ports:
      - 8080:8080
    depends_on:
      - laravel
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_port=3306
    ports:
      - 8888:80
    depends_on:
      - mysql
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
volumes:
  mysql_data: